site_name: Dore
site_url: https://dore-datagen.github.io/
site_author: Bhargav KN
site_description: >-
  Schema based fake data generator.

repo_name: dore-datagen/dore-py
repo_url: https://github.com/dore-datagen/dore-py
edit_uri: https://github.com/dore-datagen/dore-datagen.github.io/tree/master/docs

# Copyright
copyright: Copyright &copy; 2022 Bhargav KN

theme:
  logo: assets/dore-logo.svg
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.tabs.link

nav:
  - Home:
      - Getting Started: 'index.md'

  - Tutorial:
      - Overview: 'tutorial/overview.md'
      - The E-Commerce schema: 'tutorial/ecommerce_schema.md'
      - Dore Manifest:
        - Dore Manifest: 'tutorial/dore_manifest.md'
        - Creating the Manifest: 'tutorial/create_manifest.md'
        - Datastore: 'tutorial/ecommerce_datastore.md'
        - Models and Attributes: 'tutorial/models_and_attributes.md'
        - Attribute Value Definition: 'tutorial/attribute_value_definition.md'
        - Model and Attribute Properties: 'tutorial/model_and_attribute_properties.md'
        - Manifest Review: 'tutorial/ecommerce_manifest_review.md'
      - Invoking Dore:
        - Invoke Dore: 'tutorial/invoke_dore.md'
        - Manifest Variables: 'tutorial/manifest_variables.md'
        - Handling Model Conflicts: 'tutorial/handling_model_conflicts.md'
        - Multi-File Manifest: 'tutorial/multifile_manifest.md'
      - That's all Folks!:
          - Conclusion: 'tutorial/conclusion.md'

  - Reference:
      - CLI:
          - CLI Reference: 'cli/cli_reference.md'
      - Manifest:
          - Manifest: 'manifest/manifest.md'
          - Datastores:
            - Datastores: 'manifest/datastores/datastores.md'
            - Datastore Reference: 'manifest/datastores/datastore_reference.md'
            - Datastore Definition: 'manifest/datastores/datastore_definition.md'
            - Datastore Properties:
                - MySQL: 'manifest/datastores/datastore_properties_mysql.md'
                - Postgres: 'manifest/datastores/datastore_properties_postgres.md'
                - MongoDB: 'manifest/datastores/datastore_properties_mongodb.md'
                - Elasticsearch: 'manifest/datastores/datastore_properties_elasticsearch.md'
          - Models:
            - Models: 'manifest/models/models.md'
            - Model Definition: 'manifest/models/model_definition.md'
            - Model Reference: 'manifest/models/model_reference.md'
            - Model Persistence: 'manifest/models/model_persistence.md'
            - Model Properties:
              - MySQL: 'manifest/models/model_properties_mysql.md'
              - Postgres: 'manifest/models/model_properties_postgres.md'
              - MongoDB: 'manifest/models/model_properties_mongodb.md'
              - Elasticsearch: 'manifest/models/model_properties_elasticsearch.md'
          - Attributes:
            - Attributes: 'manifest/attributes/attributes.md'
            - Attribute Reference: 'manifest/attributes/attribute_reference.md'
            - Attribute Definition: 'manifest/attributes/attribute_definition.md'
            - Value Generators:
                - Faker: 'manifest/attributes/value_generator_faker.md'
                - Selector:
                  - Selector: 'manifest/attributes/value_generator_selector.md'
                  - Random Selector: 'manifest/attributes/value_generator_selector_random.md'
                  - Round Robin Selector: 'manifest/attributes/value_generator_selector_round_robin.md'
                - Ref: 'manifest/attributes/value_generator_ref.md'
                - Composite: 'manifest/attributes/value_generator_composite.md'
            - Attribute Properties:
                - MySQL: 'manifest/attributes/attribute_properties_mysql.md'
                - Postgres: 'manifest/attributes/attribute_properties_postgres.md'
                - MongoDB: 'manifest/attributes/attribute_properties_mongodb.md'
                - Elasticsearch: 'manifest/attributes/attribute_properties_elasticsearch.md'
  - About: 'about/about.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
