name: Publish site
on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create virtual env
      run: >-
        python3 -m
        venv
        venv
    - name: Activate virtual env
      run: >-
        source venv/bin/activate
    - name: Download dependencies
      run: >-
        python -m pip install -r requirements.txt
    - name: Publish
      run: >-
        mkdocs gh-deploy --remote-branch release --force
